In [17]:
import numpy as np
!pip install numpy 

In [9]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.ndim

1

In [5]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
arr.reshape(1,2,5)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [20]:
arr.reshape(2,2,5)
arr

ValueError: cannot reshape array of size 10 into shape (2,2,5)

In [21]:
arr_3d = arr.reshape(2,2,5)
arr_3d

ValueError: cannot reshape array of size 10 into shape (2,2,5)

In [25]:
arr = np.array(range(20))

In [31]:
arr2 = arr.reshape(2,2,5)
arr2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [33]:
arr2[0][1]

array([5, 6, 7, 8, 9])

In [34]:
#3D INDEXING IN NUMPY ARRAY

In [35]:
arr_3d = np.array([[[1,2,3],[4,5,6],[4,1,2],[4,5,6]]])
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [4, 1, 2],
        [4, 5, 6]]])

In [36]:
arr_3d.ndim

3

In [37]:
arr_3d.shape

(1, 4, 3)

In [40]:
arr_3d[0,1,1:3]

array([5, 6])

In [41]:
#2D arrayin numpy

In [45]:
arr_2d= np.array([[2,3],[4,5],[6,7]])
arr_2d.shape


(3, 2)

In [46]:
arr_2d.ndim

2

In [47]:
arr_2d

array([[2, 3],
       [4, 5],
       [6, 7]])

In [56]:
arr_2d[0:3,1]

array([3, 5, 7])

In [ ]:
#Data types in numpy 

In [57]:
arr_2d.dtype

dtype('int32')

In [62]:
arr_ch = np.array([65,99,'Hello World', 9])

In [63]:
arr_ch.dtype

dtype('<U11')

In [64]:
arr_ch[2]

'Hello World'

In [65]:
arr_ch[2].dtype

dtype('<U11')

In [66]:
arr_ch

array(['65', '99', 'Hello World', '9'], dtype='<U11')

In [69]:
arr_ch = np.array(['65', '99', 'Hello World', '9'], dtype='S')

In [70]:
arr_ch

array([b'65', b'99', b'Hello World', b'9'], dtype='|S11')

In [71]:
arr_ch[2]

b'Hello World'

In [72]:
arr_ch[2].decode()

'Hello World'

In [73]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr_2dg = arr1.reshape(5,2)
arr_2dg

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [76]:
import time

In [77]:
for row in arr_2dg:
    print(row)
    time.sleep(1)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [78]:
for row in arr_2dg:
    for element in row:
        print(element)
    time.sleep(1)    

1
2
3
4
5
6
7
8
9
10


In [79]:
arrr = np.array([1,2,3])

In [80]:
for x,y in np.ndenumerate(arrr):
    print(x,y)
    

(0,) 1
(1,) 2
(2,) 3


In [81]:
#spliting arrays in numpy 

In [96]:
arrr1 = np.arange(1,10)
arrr1
print(np.split(arrr1,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [85]:
np.split(arrr1,9)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [92]:
np.split(arrr1,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [100]:
g=np.array_split(arrr1,4)
print(g)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [101]:
#Random varible using in Numpy 

In [105]:
from numpy import random
x = random.randint(100)
print(x) #This X is change every time whenever you run it

24


In [110]:
x1 = random.randint(100,size = (3,3))
print(x1) #Every time this matrix values will change 

[[82 23 73]
 [37 99 27]
 [64 44 56]]


In [114]:
#print 0 to 1 float values 
random.rand()

0.9292384685926549

In [115]:
random.rand(7)

array([0.93920189, 0.33833609, 0.79076345, 0.6333995 , 0.59169833,
       0.8734298 , 0.78261781])

In [119]:
#print random choice number
random.choice([1,2,3,4,5,5,6,7,8,9])

7

In [123]:
random.choice([1,2,3,4,5,5,6,7,8,9],size=(2,2))

array([[1, 3],
       [1, 5]])

In [126]:
random.choice([1,2,3,4,5,5,6,7,8,9],size=(5,3))

array([[3, 1, 4],
       [3, 1, 9],
       [9, 5, 4],
       [1, 6, 8],
       [6, 1, 4]])

In [131]:
x4=random.choice([1,2,3,4],p=[0.2,0.3,0.5,0.6],size=(2,2))

ValueError: probabilities do not sum to 1

In [132]:
g = np.array([3,79,9,7,5,6])

In [135]:
random.permutation(g)

array([79,  9,  6,  3,  5,  7])

In [2]:
import numpy as np

In [3]:
L = [1,2,3,4]

In [4]:
ar = np.array(L)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
L

[1, 2, 3, 4]

In [7]:
L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
ar * 2

array([2, 4, 6, 8])

Complex number in Numpy 

In [9]:
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [10]:
a = np.array([[1,2,3],[0,1,4]])

In [11]:
b = np.zeros((2,3), dtype = np.int16)

In [12]:
c = np.ones((2,3), dtype = np.int16)

In [13]:
d = a+b+c

In [14]:
print(d[1,2])

5


In [15]:
array = np.array([
               [3,7,1],
               [10,3,2],
               [5,6,7]])
print(array)

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]


In [16]:
print()

In [19]:
print(np.sort(array, axis = None))

[ 1  2  3  3  5  6  7  7 10]


In [20]:
print(np.sort(array, axis = 1))

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]


In [22]:
print(np.sort(array, axis = 0))

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


In [5]:
a_scaler = np.array(20) 
a_scaler
print(a_scaler)

20


In [7]:
type(a_scaler)

numpy.ndarray

In [9]:
a_scaler.ndim

0

In [12]:
#vector
a_vector = np.array([1,2,3,4,5,6])
print(a_vector)

[1 2 3 4 5 6]


In [13]:
a_vector.ndim

1

In [14]:
a_vector.shape

(6,)

In [15]:
#matrix
a_matrix = np.array([[1,2],[3,4]])
print(a_matrix)

[[1 2]
 [3 4]]


In [16]:
a_matrix.ndim

2

In [18]:
a_matrix.shape #(2,2) is (2 rows, 2 columns)

(2, 2)

In [21]:
sample_vector = np.arange(1,11) 
print(sample_vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
sample_vector[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [41]:
sample_matrix = np.arange(1,10).reshape(3,3)
print(sample_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
sample_matrix.shape


(3, 3)

In [43]:
sample_matrix.shape[0] #axis 0 is rows(y)

3

In [44]:
sample_matrix.shape[1] #axis 1 is columns(x)

3

In [45]:
sample_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [55]:
sample_matrix[1:3,2:3]

array([[6],
       [9]])

In [56]:
sample_matrix[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [57]:
sample_matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [62]:
sample_matrix[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [67]:
sample_matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [69]:
#tensor

a_tensor = np.arange(1,28).reshape(3,3,3)
print(a_tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [70]:
a_tensor.ndim

3

In [4]:
a = np.array([[2,3], [4,5], [6,9]])
print(a)

[[2 3]
 [4 5]
 [6 9]]


In [5]:
b = np.array([[1,2,3],
              [4,5,6]])

c = np.array([[10,11,12],
              [13,14,15]])

D = b + c
print(D)

[[11 13 15]
 [17 19 21]]


In [7]:
A = [[6,7],
    [8,9]]

B = [[1,3],
    [5,7]]

print(np.dot(A,B))

[[41 67]
 [53 87]]


In [12]:
import numpy as np

b = np.identity(2, dtype = float)
print("Matrix b : \n", b)

c = np.identity(4)
print("\nMatrix a : \n", c)


Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)
print(arr)

print("##################################")

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
##################################
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
x = np.array([5, 6, 7 ,4 , 3, 2, 1])
y = 2 >= x
print(y)

[False False False False False  True  True]


In [26]:
og_arr = np.array([[11.21, 19.21], [46.21, 18.23], [29.21, 21.21]])
print(og_arr)

print("After coverting  numpy float array to int array")
int_array = og_arr.astype(int)
print(int_array)

[[11.21 19.21]
 [46.21 18.23]
 [29.21 21.21]]
After coverting  numpy float array to int array
[[11 19]
 [46 18]
 [29 21]]


In [29]:
in_arr1 = np.array([1, 2, 3])
print("1st Input array : \n ", in_arr1)

in_arr2 = np.array([4, 5, 6])
print("2nd Input array : \n ", in_arr2)

out_arr = np.vstack((in_arr1, in_arr2))
print("\n Output horizontally stacked array:\n  ", out_arr)

1st Input array : 
  [1 2 3]
2nd Input array : 
  [4 5 6]

 Output horizontally stacked array:
   [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
list = [x for x in range(0, 257, 3)]

n = np.array(list)

print(n)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255]


In [5]:
list2 = [x for x in range(0, 51, 2)]

n = np.array(list2)

print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
